### ISSUE TITLE
"ext-id" prompt doesn't work with scoped name

### ISSUE THREAD

**Issue by IlCallo** [quasarframework/quasar-starter-kit-app-extension#15]
**Describe the bug**
In the docs it's written that

> `ext-id` for `@some-npm-org/quasar-app-extension-awesomeness` is `@some-npm-org/awesomeness`

but when creating the repo with this starter kit, the prompt won't work with scoped `ext-id`.

If I provide `@some-npm-org/awesomeness`, the package name into `package.json` will be generated as `quasar-app-extension-@some-npm-org/awesomeness` instead of `@some-npm-org/quasar-app-extension-awesomeness`

**To Reproduce**
1. Create a new app extension
2. Provide `@some-npm-org/awesomeness` as `ext-id`
3. Notice it generates `quasar-app-extension-@some-npm-org/awesomeness` package name

**Expected behavior**
It should generate `@some-npm-org/quasar-app-extension-awesomeness`

**Platform (please complete the following information):**
OS: Ubuntu 18.04
Node: 12.14.0
NPM: 6.13.4
Yarn: 1.22.4

**Comment by smolinari** [comment]
I did some digging myself. The ext-id [should only be the short name](https://github.com/quasarframework/quasar-starter-kit-app-extension/blob/4b5a006dccf9aa5fb01d6d7a3ff0c2a83ac4ea86/template/package.json#L2). To then get the scope added the dev would need to run 

`npm init --scope=@my-org`

in the AE's source folder or just go into package.json and update the package name. 

Or, the `create` process needs to take a scoped package name into account. 

Scott
